# Generated by Django 5.2.11 on 2026-02-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('can_export_data', 'Can export study data'), ('can_edit_survey_questions', 'Can edit survey questions'), ('can_edit_consent_documents', 'Can edit consent documents'), ('can_process_deletion', 'Can process deletion requests')]},
        ),
    ]
