# Generated by Django 5.2.11 on 2026-02-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_participant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='accounts.participant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'sent_at'], name='accounts_re_partici_9d8799_idx')],
            },
        ),
    ]
