# Generated by Django 5.2.11 on 2026-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('recorded_at', models.DateField()),
            ],
            options={
                'ordering': ['-recorded_at', 'event_type'],
                'indexes': [models.Index(fields=['event_type', 'recorded_at'], name='accounts_me_event_t_41e14a_idx')],
                'unique_together': {('event_type', 'recorded_at')},
            },
        ),
    ]
