# Generated by Django 5.2.11 on 2026-03-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditevent_event_type'),
        ('challenges', '0004_add_clarification_to_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('unclear_description', 'Unclear description'), ('wrong_test_case', 'Wrong or unexpected test case'), ('broken_skeleton', 'Broken skeleton code'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Internal notes on how the report was resolved. Reference DEVIATIONS.md entries here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='challenges.challenge')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_reports', to='accounts.participant')),
            ],
            options={
                'indexes': [models.Index(fields=['challenge'], name='challenges__challen_0024b5_idx'), models.Index(fields=['resolved'], name='challenges__resolve_0005d9_idx')],
            },
        ),
    ]
